/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppBehaviorRouteImport } from './routes/_app.behavior'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppScenariosRouteImport } from './routes/_app.scenarios'
import { Route as AppAlertsIndexRouteImport } from './routes/_app.alerts.index'
import { Route as AppAlertsAlertIdRouteImport } from './routes/_app.alerts.$alertId'
import { Route as AppPatientsIndexRouteImport } from './routes/_app.patients.index'
import { Route as AppPatientsPatientIdRouteImport } from './routes/_app.patients.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppBehaviorRoute = AppBehaviorRouteImport.update({
  id: '/behavior',
  path: '/behavior',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRoute = AppScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsIndexRoute = AppAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsAlertIdRoute = AppAlertsAlertIdRouteImport.update({
  id: '/alerts/$alertId',
  path: '/alerts/$alertId',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsPatientIdRoute = AppPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AppAuditRoute
  '/behavior': typeof AppBehaviorRoute
  '/overview': typeof AppOverviewRoute
  '/scenarios': typeof AppScenariosRoute
  '/alerts/$alertId': typeof AppAlertsAlertIdRoute
  '/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/alerts/': typeof AppAlertsIndexRoute
  '/patients/': typeof AppPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AppAuditRoute
  '/behavior': typeof AppBehaviorRoute
  '/overview': typeof AppOverviewRoute
  '/scenarios': typeof AppScenariosRoute
  '/alerts/$alertId': typeof AppAlertsAlertIdRoute
  '/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/alerts': typeof AppAlertsIndexRoute
  '/patients': typeof AppPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/audit': typeof AppAuditRoute
  '/_app/behavior': typeof AppBehaviorRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/scenarios': typeof AppScenariosRoute
  '/_app/alerts/$alertId': typeof AppAlertsAlertIdRoute
  '/_app/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/_app/alerts/': typeof AppAlertsIndexRoute
  '/_app/patients/': typeof AppPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/behavior'
    | '/overview'
    | '/scenarios'
    | '/alerts/$alertId'
    | '/patients/$patientId'
    | '/alerts/'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/behavior'
    | '/overview'
    | '/scenarios'
    | '/alerts/$alertId'
    | '/patients/$patientId'
    | '/alerts'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/audit'
    | '/_app/behavior'
    | '/_app/overview'
    | '/_app/scenarios'
    | '/_app/alerts/$alertId'
    | '/_app/patients/$patientId'
    | '/_app/alerts/'
    | '/_app/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/behavior': {
      id: '/_app/behavior'
      path: '/behavior'
      fullPath: '/behavior'
      preLoaderRoute: typeof AppBehaviorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scenarios': {
      id: '/_app/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof AppScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts/': {
      id: '/_app/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AppAlertsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts/$alertId': {
      id: '/_app/alerts/$alertId'
      path: '/alerts/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AppAlertsAlertIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/': {
      id: '/_app/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId': {
      id: '/_app/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AppPatientsPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppBehaviorRoute: typeof AppBehaviorRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppScenariosRoute: typeof AppScenariosRoute
  AppAlertsAlertIdRoute: typeof AppAlertsAlertIdRoute
  AppPatientsPatientIdRoute: typeof AppPatientsPatientIdRoute
  AppAlertsIndexRoute: typeof AppAlertsIndexRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppBehaviorRoute: AppBehaviorRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppScenariosRoute: AppScenariosRoute,
  AppAlertsAlertIdRoute: AppAlertsAlertIdRoute,
  AppPatientsPatientIdRoute: AppPatientsPatientIdRoute,
  AppAlertsIndexRoute: AppAlertsIndexRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
